docs/index.rst

This looks wrong (at http://yarl.readthedocs.io/en/latest/):
and I hope I got the Sphinx syntax right to fix it.

Fix reference to method in docs

---

requirements-dev.txt

Otherwise you have error when pip install requirements-dev
```
pip install -r requirements-dev.txt
Double requirement given: cython==0.25.1 (from -r requirements-dev.txt
(line 3)) (already in cython==0.25.1 (from -r requirements-wheel.txt
(line 1)), name='cython')
```

Fix double cython requirement

---

setup.py

This PR load pytest runner only if need. Without that you need an internet access to execute setup.py install even if the dependencies are already installed.
The code for detecting if require is from section Conditional Requirement:
https://pypi.python.org/pypi/pytest-runner

Load pytest-runner only if mandatory

---

tests/test_url.py
yarl/__init__.py

The problem occurs when I load the instance URL from pickle old session.

Load from pickle without _cache

---

appveyor.yml

Without this pip installing aiohttp is absolutely sure to fail.

Added Python 3.6 for needed wheels for Python 3.6

---

.travis.yml
build-wheels.sh

This should fix everything to deal with Python 3.6 wheel building on linux.

Fix Python 3.6 builds in travis.

---

tests/test_quoting.py
yarl/_quoting.pyx
yarl/quoting.py

"+" is entirely legal in URL paths.  Unfortunately unquote() does the wrong thing.  This patch fixes that.  It also adds a test for quote(qs=False) for "+", to be sure it continues to do the right thing.

Do not quote or unquote + if not a query string.

---

tests/test_url.py
yarl/__init__.py

In current version of yarl we have problem with query args unquoted twice. So If you will pass URL as argument, it will be broken. This PR fixes the problem.

Prevent double unquoting

---

tests/test_url.py
yarl/__init__.py

This pull request solves the bug of leading slash in URL path.
**How to reproduce?**
```
>>> from yarl import URL
>>> u = URL('http://example.com/path').with_path('new/path')
>>> str(u)
'http://example.com/new/path'
>>> u.path
'new/path'
```
Expecting result is: ``` u.path == '/new/path'```
**Why does this matter?**
This creates a side effect for other methods:
```
>>> u.parts
('/', 'ew', 'path')
>>> u.with_name('name')
URL('http://example.com/ew/name')
```
This creates an incorrect HTTP request header:
```
import asyncio
from aiohttp import ClientSession
from yarl import URL
u = URL('http://bbc.com/news').with_path('sport')
async def main():
async with ClientSession() as session:
async with session.get(u):
pass
asyncio.get_event_loop().run_until_complete(main())
```
```
Traceback (most …
```

Fix with_path leading slash.

---

tests/test_update_query.py
yarl/__init__.py

Current behaviour of YARL does not encode the `;` parameter when it is present in the QS param value. The `;` is not a safe parameter and has to be encoded [1].
The following snippet shows the error (raised via aiohttp):
```python
from yarl import URL
url = URL("http://www.google.com").with_fragment(None)
params = {'foo': 'a;b'}
url2 = url.with_query(params)
url2.query
```
This snippet gets as an output an "invalid" MultiDict
```
<MultiDictProxy('foo': 'a', 'b': '')>
``` 
[1] https://tools.ietf.org/html/rfc3986#section-2.2

Unsafe encoding for QS fixed. Encode `;` char in value param

---

tests/test_update_query.py
yarl/__init__.py

Close issue https://github.com/aio-libs/yarl/issues/87:
- share implementation
- fixed `TypeError` (`URL('test').update_query(a=1)`)
Benchmark at `master`:
```
Cython quote: 1.361 sec
Python quote: 4.641 sec
Cython unquote: 0.520 sec
Python unquote: 1.682 sec
```
Benchmark at my branch:
```
Cython quote: 1.340 sec
Python quote: 4.428 sec
Cython unquote: 0.495 sec
Python unquote: 1.626 sec
```

Share `update_query()` implementation with `with_query()`

---

.gitignore
docs/api.rst
tests/test_url.py
yarl/__init__.py
yarl/__init__.pyi

https://github.com/aio-libs/yarl/issues/136

Add raw_path_qs attribute

---

CHANGES.rst
tests/test_normalize_path.py
tests/test_url.py
yarl/__init__.py

E.g. DNS contains underscore character

Fallback to IDNA 2003 if domain name is not IDNA 2008 compatible

---

.gitignore
CHANGES.rst
Makefile
benchmark.py
tests/test_quoting.py
yarl/__init__.py
yarl/_quoting.pyx

Use fast path if quoted string doesn't require requoting

Optimization

---

tests/test_url.py
yarl/__init__.py

yarl.URL was always considered as **final** class.

Forbid inheritance, replace __init__ with __new__

---

yarl/__init__.pyi

I have code like this to avoid having ports being redundantly part of my base urls:
```python
port = None if (req.port in _DEFAULT_PORTS) else req.port
req.base_url = URL.build(
host=req.forwarded_host, scheme=req.forwarded_scheme, port=port
)
```
and that currently gives me an `error: Argument "port" to "build" of "URL" has incompatible type "Optional[Any]"; expected "int"` although None is perfectly valid and also defined as optional on the class.
(this is Falcon in case you wondered)

Make port argument to URL.build optional in stub

---

tests/test_quoting.py

Using `\xYZ' in Unicode string literals can be a source of confusion, as
`\xYZ` escpaing in commonly used for byte escaping and not character
escaping.
Using `\u00YZ` on the other hand, is more clear and won't be misleading
any reader about the intention.

Replace \x usage for Unicode character escaping with \u

---

tests/test_url_build.py
yarl/__init__.py

Accept host-only URLs, which are buildable using the parsing method as
`//host-name'.
Also, add check for setting port without a host, along-side test case
for it.

URL::build(): Accept host-only URLs

---

docs/api.rst
tests/test_url.py
yarl/__init__.py

Having access to `explicit_port` makes it easier for working with the
URL instance as a data model, like when building mutable class on top of
`yarl.URL`.
On the other hand, the existing behavior of `port` property is better
for the applications. Therefore, it's better that we keep it the way it
is.

URL: Add explicit_port instance property

---

yarl/__init__.py

Fixes #168 
Few tests for bad port scenario are already present in `test_url_parsing.py`, they already cover current situation.

Issue#168: give friendlier error when port cant be converted to int

---

tests/test_quoting.py

**What has been done:**
1. Add raw string identifier - to fix "DeprecationWarning: invalid escape sequence \^"
(SHOULD_QUOTE remains the same)
2. `~` was missing from unquoted chars
3. I think `quoter(qs=True)(do_not_quote) == do_not_quote` without assert was unintended.
It could be the wrong place to ask, but... 
**Some questions**
4. `SHOULD_QUOTE` and `do_not_quote` - why not import from `quoting.py`, it has vars with the same meaning.
5. `test_quoting.py` has one todo item: `# TODO: should it encode percent?`
According to `rfc3986` it has to be encoded. 
Maybe the main concern is to do it's encoding/decoding only once? In that case it deserves its own issue.
6. does `assert s1 is s2` from `def test_quote_fastpath_safe():` has to be `is` instead of `==`?
I read this note about [cython …

Minor fixes in test_quoting.py

---

.travis.yml

Now nightly is essentially the same as 3.8, and will be until Python 3.8 beta.
Let's drop redundant duplication.

Drop explicit py3.8 Travis rule

---

tests/test_url.py
yarl/__init__.py

Unlike `urllib.parse.urlsplit`, `yarl.URL` currently does not distinguish `http://user@localhost` and `http://user:@localhost`, returning `None` as `url.password` in both cases. I think that these cases are different and should be handled similar to `urllib.parse.urlsplit` function.

Support empty password in URL

---

tests/test_url_build.py
yarl/__init__.py

Unsupported and results in strange behavior of equality operator. See
issue #275.

Disallow passing NoneType to URL.build

---

CHANGES.rst
yarl/__init__.py
yarl/__init__.pyi

Fix type-check warnings when passing `Optional` arguments to URL.build.
Changes related only to static type checking.
* The format is `<Name> <Surname>`.
* Please keep alphabetical order, the file is sorted by names. 

Allow user=None in URL.build and sync .pyi with source.

---

README.rst
docs/_templates/about.html
docs/conf.py
docs/index.rst
requirements/doc-spelling.txt
tools/build-wheels.sh

Badge on the README and readthedocs currently says the build is failing. However, it's pointing to travis, which was obviously replaced with azure pipelines.
This PR replaces travis references and badges with azure pipelines.
Nope.
N/A

Update build badges and CI references

---

yarl/__init__.py

This would allow for checking if `host` contains only ASCII characters with Python 3.6 and 3.5. 
Performance tests with `%timeit` in `ipython` on Python 3.6 show that this check takes about 0.18 μs, if the first character in `host` is non-ASCII. 0.87 μs if the 10th character is the first non-ASCII character and 1.46 μs if the 20th character is non-ASCII. The times are about the same, if `host` is purely ASCII and 1, 10 or 20 characters long, respectively. 
While this is quite a bit slower than `str.isascii()` on Python 3.8 on the same machine (about 0.038 μs, independ of length or position of the characters) it is about 25 times faster than running IDNA encoding needlessly: for 20 characters `idna.encode(host, uts46=True).decode("ascii")` takes about 40 μs if `host` is ASCII.
If some …

Workaround for missing str.isascii() in Python 3.6

---

docs/api.rst

Do this because it confused me when I tried to read the docs.
Fix a typo in the user documentation.
No.
No.

Fix an arg mistake in the `with_fragment()` method signature doc

---

CHANGES/443.feature
docs/api.rst
tests/test_update_query.py
yarl/__init__.py

These changes resolve aio-libs/aiohttp#4714.
Yes, users can now use lists or tuples when quoting mappings.

Support quoting list values in mappings

---

CHANGES/451.bugfix
tests/test_url_update_netloc.py
yarl/__init__.py

Keep ipv6 brackets after updating port/user/password
close #451 

Keep ipv6 brackets after updating port/user/password

---

CHANGES/426.bugfix
tests/test_quoting.py
tests/test_update_query.py
yarl/__init__.py
yarl/_quoting.pyx
yarl/quoting.py

These changes fix a bug where query component, passed in a form of mapping or sequence, is unquoted in unexpected way.
```python
def test_with_query_complex_url():
target_url = "http://example.com/?game=bulls+%26+cows"
url = URL("/redir").with_query({"t": target_url})
assert url.query["t"] == target_url
```
User will now be able to use any string as query component in `URL.with_query`, `URL.update_query` and `URL.build`.
Which will be properly encoded.
Fixes #426 
* `.removal`: Signifying a …

fix requoting query components

---

CHANGES/484.misc
requirements/test.txt
setup.py
yarl/__init__.pyi

They make it possible to run on py3.8+ without external `typing_extensions`. This also fixes support for py3.9 where typing_extensions don't work (yet).
Nope.
Nope.

Require typing_extensions for py<3.8 only

---

CHANGES/502.bugfix
CHANGES/504.bugfix
tests/test_url.py
tests/test_url_build.py
tests/test_url_update_netloc.py
yarl/_url.py

Keep IPv6 brackets in origin().
Closes #502.
Closes  #504.

Do not requote arguments of URL.build() and with_xxx()

---

Makefile

**black** 20.8b1 adds by default a trailing comma in a function definition (actually this feature is not stable). This syntax is not compatible with Python 3.5.

Make black compatible with Python 3.5

---

CHANGES/511.bugfix
tests/test_url.py
yarl/_url.py

It now %-encodes delimiters and non-printable characters and works correctly with IPv6 addresses.
Closes #511.

Fix `URL.human_repr()` to always return URLs equivalent to the source

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.md

-----
[View rendered .github/ISSUE_TEMPLATE/bug_report.md](https://github.com/aio-libs/yarl/blob/maintenance/issue-templates/.github/ISSUE_TEMPLATE/bug_report.md)
[View rendered .github/ISSUE_TEMPLATE/feature_request.md](https://github.com/aio-libs/yarl/blob/maintenance/issue-templates/.github/ISSUE_TEMPLATE/feature_request.md)

Migrate issue templates from aiohttp and link discussions

---

CHANGES/514.bugfix
tests/test_quoting.py
yarl/_quoting_c.pyx

Fixed cases "%%xx" and "%a%xx".
Closes #514.

Fix the Cython implementation for requoting a single percent.

---

CHANGES/516.bugfix
CHANGES/520.bugfix
tests/test_quoting.py
yarl/_quoting_c.pyx
yarl/_quoting_py.py

* No longer raise ValueError for % followed by non-hexdigits.
* Fix decoding % followed by a space and hexdigit.
Closes #516.
Closes #520.

Fix some errors in unquoter

---

CHANGES/528.bugfix
yarl/__init__.pyi

Fix annotation of with_query()/update_query() methods for key=[val1, val2] case

---

docs/_templates/about.html
docs/conf.py

Delete the Azure Pipelines badge from the docs
Resolves #569

Delete the Azure Pipelines badge from the docs

---

CHANGES/623.bugfix.rst
tests/test_url_update_netloc.py
yarl/_url.py

Fixes reencoding of URL elements after calling with_port().
No.
Fixes #620.

Stop reencoding URL when calling with_port()

---

CHANGES/646.misc
setup.py

This does not affect source distributions, and Cython sources (`.pyx`) are
still installed.
Fixes #646.
Prevent C sources (`_quoting_c.c`) from being included in binary distributions such as wheels, without affecting Cython sources (`_quoting_c.pyx`, `_quoting_c.pyi`) or source distributions.
Nothing changes except that the binary wheels are smaller because they do not contain `_quoting_c.c`.
https://github.com/aio-libs/yarl/issues/646
* …

Do not install C sources with binary distributions

---

.pre-commit-config.yaml
CHANGES/699.misc.rst

Unauthenticated `git://` URLs are no longer supported by GitHub:
```
fatal: remote error: 
The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
```

Don't use `git://` URLs in pre-commit hooks

---

.pre-commit-config.yaml
CHANGES/701.misc.rst
tests/test_quoting.py

Move to the stable release and pin click, as black used the wrong exception to
work around a click interaction causing issues. See https://github.com/psf/black/issues/2964

Unbreak black

---

.github/workflows/ci.yml
CHANGES/700.misc.rst

When someone force-pushes to a PR or adds a new commit, the workflow would run
_twice_, as both `push` and `pull_request` events would trigger.
The default for `types` is `[opened, reopened, synchronize]`; the latter is the
type that overlaps with `push`.

Avoid running the workflow twice on PR pushes

---

.pre-commit-config.yaml
CHANGES/702.misc.rst

This release fixes the issues that required pinning click, so we can drop that
pin again.

Upgrade black to 22.3.0

---

.github/workflows/ci.yml
CHANGES/703.misc.rst

The current filter is way too broad, and uses invalid syntax. See the [Github
filter cheat
sheet](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet).

Fix the workflow backport filter

---

.github/workflows/ci.yml
CHANGES/694.misc.rst

This bumps `checkout` and `setup-python` versions in the GitHub actions configuration to **v3** and simplifies dependency caching.
No.
No.

Simplified caching in Github actions configuration.

---

CHANGES/739.misc.rst
docs/conf.py

Change the Sphinx `language` parameter from `None` to `en`, explicitly setting
the language.
All documentation is in English, and Sphinx 5 complains loudly if this isn't
set.
#733, a dependabot PR that upgrades Sphinx to 5.0.1. The CI lint step fails due
to the warning.
* Make sure to use full sentences with correct case and punctuation, for example: `Fix issue with …

Explicitly set a language

---

.github/workflows/ci.yml

With Cython upgraded to include 3.11 support, the test should pass cleanly.

CI: Also test on 3.11 alpha with Cython

---

.github/workflows/ci.yml

Upgrade the CI with newer interpreters

---

CHANGES/793.bugfix.rst
tests/test_update_query.py
tests/test_url_update_netloc.py
yarl/_url.py

These changes fix the improper validation issues with URL.with_port(). Essentially, it restricts ports to be from 0 to 65535 (tcp limit), and fixes the weird handling of the 0 port
The URL.with_port() function will now throw errors when Booleans or invalid ports are arguments.
#746 
Currently, this is set up to allow port 0 to function and not throw errors. From what I looked up it seems to be possible to use the 0 port (officially it does "not exist"), though since it's a special case and issue #746 says that the output should throw an error, I'm unsure if I'm handling it correctly. …

Fix to URL.with_port() input filtering

---

CHANGES/790.bugfix.rst
CHANGES/792.bugfix.rst
tests/test_update_query.py
yarl/_url.py

This fixes the query_update() function special case where the None argument should clear query.
The query_update() function now works when None is passed to the function.
#723 

Fix to query_update(None)

---

CHANGES/808.bugfix.rst
tests/test_url_build.py
yarl/_url.py

Make `URL.build()` raise a `TypeError` if `host` argument is `None`
No.
#808

`URL.build()`: Raise `TypeError` if `host` argument is `None`

---

.pre-commit-config.yaml

See PyCQA/isort#2077; will leave it to the pre-commit update bot
to push this to 5.12.

Update isort in pre-commit deps to unbreak linting

---

LICENSE
NOTICE

This PR partially reverts the change made in https://github.com/aio-libs/yarl/commit/94faa90c3c3e6d8ac519fa4b6bee154bc090e34b to remove the text of the Apache license used. This brings this repository in line with [Apache guidance](https://www.apache.org/licenses/LICENSE-2.0#apply) on this:
```
Include a copy of the Apache License, typically in a file called LICENSE, in your work, and consider also including a NOTICE file that references the License.
```
This PR copies best practice as shown in Apache libraries, such as https://github.com/apache/zookeeper/blob/master/LICENSE.txt & https://github.com/apache/flink/blob/master/LICENSE as well as other non-apache libraries which use this license such as https://github.com/Activiti/Activiti/blob/develop/LICENSE.txt & …

Update the LICENSE file to contain the license used (Apache-2.0) and add a NOTICE file referencing it

---

requirements/ci.txt

Tests don't need to have the doc requirements installed, and we can't
move to modern doc tools while also supporting 3.7 in tests.

ci: remove docs from the ci requirements for tests

---

.pre-commit-config.yaml

The current releases of black have long since moved beyond the issue.

ci: Remove long-obsolete black dependency

---

CHANGES/845.bugfix.rst
yarl/_url.py

The documentation states that `url.update_query(None)` clears the query string.
However, that means that _other valid arguments_, such as `{}`, should not.
This behaviour was recently fixed in #792, but this specific edgecase was then
introduced. We haven't released a version with that change included, however.
* Make sure to use full sentences with correct case and …

update_query({}) should be a no-op.

---

CHANGES/832.feature.rst
tests/test_url.py
yarl/_url.py

Allows external classes to extend functionality properly using `__rtruediv__`.
Previously, `URL` would raise a not-so-nice error like this:
```python
>>> from yarl import URL
>>> 
>>> u = URL('https://beefslab.com/abc')
>>> u
URL('https://beefslab.com/abc')
>>> u / 3
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/home/peters/.env38/lib/python3.8/site-packages/yarl/_url.py", line 318, in __truediv__
name = self._PATH_QUOTER(name)
File "yarl/_quoting_c.pyx", line 213, in yarl._quoting_c._Quoter.__call__
TypeError: Argument should be str
```
Now, it will properly return NotImplemented (still eventually resulting in a TypeError).
```python
>>> u / 3
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for …
```

Support External Classes' `__rtruediv__`

---

CHANGES/850.bugfix.rst
tests/test_url_query.py

In Python 3.7 patch releases before 3.7.10, 3.8 patch releases before
3.8.8 and 3.9 patch releases before 3.9.2, URL parsing will split
parameters on semicolons but this is no longer valid as of RFC3986 and
is a security issue.
The patch remedying this introduced a new parameter, `separator`, which
we use to detect wether or not the test will fail.
Fixes #850, unblocking the release process.
The markers were tested locally using Python 3.7.9, 3.8.7 and 3.9.1, as well as
newer patch releases of those Python versions.

Mark semicolon-based tests as xfail in specific cases

---

CHANGES.rst
CHANGES/850.bugfix.rst
yarl/__init__.py

Since 1.9.0 failed to release, lets release 1.9.1 now that the tests will also
pass on 2.7.9 as used by cibuildwheels.

Bump the project version to 1.9.1

---

CHANGES/854.bugfix.rst
tests/test_url.py
yarl/_url.py

When joining path elements against an absolute URL, ensure that
the resulting path starts with a slash.
Fixes #854

Fix truediv joining against absolute URL with no path

---

CHANGES/862.bugfix.rst
tests/test_url.py
yarl/_url.py

This fixes the regression in `URL.joinpath` that stopped it from preserving a trailing slash in the path components to be joined.
A statement like `URL("http://example.com") / "foo/"` will again preserve the trailing slash.
Fixes #862 
* Make sure to use full sentences with correct case and punctuation, for example: `Fix issue with non-ascii contents in doctest text …

Keep a trailing slash in URL.joinpath

---

CHANGES/886.misc.rst
pyproject.toml

Before this patch, the legacy fallback was being selected automatically. This is not what we want and we should make use of the actual modern implementation.

🎨 Explicitly use setuptools PEP 517 build backend

---

pyproject.toml

It is auto-added by `setuptools`' build backend when building wheels but is absolutely unnecessary when building an sdist.

🔥 Drop `wheel` from sdist build deps

---

CHANGES/890.misc.rst
setup.cfg
setup.py

This cleans up `setup.py`, keeping only things that are hard to move. It puts all possible attrs into `setup.cfg`. It doesn't attempt making use of `pyproject.toml` for this purpose because it's easier to maintain separate configs in dedicated files, on scale.

📦🎨 Move package attrs to declarative config

---

CHANGES/876.bugfix.rst
tests/test_url.py
tests/test_url_parsing.py
yarl/_url.py

- The human representation of usernames and passwords should percent-encode square brackets.
- Clean up the test suite to remove tests that use invalid hostnames (square brackets in a host name must only be used for IPv6 addresses).
- Rename the remaining test using IPvFuture address syntax to make this explicit.
- Drop a test for IPv6 addresses with a zone id; zone id support is controversial and expilictly excluded from the WHATWG URL standard.  Zone ids *without percent characters in their name* continue to work as long as `urllib.parse.urlsplit()` accepts them but this is not something that yarl.URL() needs to support explicitly.
Fixes #876

Correct square bracket handling in URL netloc

---

.github/workflows/ci-cd.yml
CHANGES/942.misc.rst
CHANGES/942.packaging.rst
setup.cfg

Communicates official support for Python 3.12
No

feat: Support Python 3.12

---

CHANGES/822.contrib.rst
tests/test_url_parsing.py

Adds a test to ensure that empty hosts are handled in the correct way, as requested in #821.

Add test for empty host #821

---

docs/api.rst

Make it clear that `with_scheme` can change the port.
No
No

Document default port substitution on URL.with_scheme

---

.coveragerc
.github/workflows/ci-cd.yml
.github/workflows/reusable-build-wheel.yml
CHANGES/961.contrib.rst
docs/spelling_wordlist.txt
requirements/test.txt

🧪 Collect Cython coverage in CI

---

.github/workflows/ci-cd.yml
.github/workflows/reusable-build-wheel.yml
.github/workflows/reusable-linters.yml
.readthedocs.yaml
CHANGES.rst
CHANGES/962.contrib.rst
CHANGES/963.packaging.rst
Makefile
README.rst
docs/index.rst
docs/spelling_wordlist.txt
packaging/pep517_backend/_backend.py
pyproject.toml
tools/build-wheels.sh

Since these are not CLI options, there's no need to prefix them as ones. It is also less confusing to the unsuspecting reader.

📦 Simplify build settings dropping leading `--`

---

CHANGES/883.bugfix
tests/test_url_build.py
yarl/_url.py

Using port="" resulted in malformed urls, now using string for port raises TypeError
URL.build does not accept strings as port any longer.
URL.build does not create invalid urls when using "" as value for port.
fix #883

Raise `TypeError` when a string is passed for `port` to `URL.build()`

---

CHANGES/981.doc.rst
CHANGES/README.rst

_Hello @webknjaz,_
There's one more broken link to fix.
These changes fix a broken link to `towncrier`'s philosophy.
Link from [Contributing docs](https://yarl.aio-libs.org/en/latest/contributing/guidelines/#adding-change-notes-with-your-prs) to `towncrier`'s philosophy will be fixed.
Similar PR:
* aio-libs/frozenlist#574

Fix the Towncrier philosophy link

---

CHANGES/1014.packaging.rst
CHANGES/992.packaging.rst
docs/conf.py
packaging/pep517_backend/_backend.py

Previously, setting `TMPDIR="$(pwd)/smth-inside"` would cause the
in-tree PEP 517 build backend to go into infinite recursion,
attempting to copy the project directory into a nested folder.
Specifically, this is happening in the Fedora land because macros
used in RPM packaging (`pyproject-rpm-macros`) are setting it up
like this. Additionally, this is only happening with `pip wheel` and
doesn't affect `pyproject-build`, because the latter pre-copies the
project directory by itself early, and changes current working
directory to it while the former does not.
This patch addresses the issue by excluding the temporary directory
from traversal when copying the directory tree within the build
backend.
Fixes #992.

Prevent copying tmp dir to itself in build backend

---

.github/workflows/ci-cd.yml
CHANGES/1015.contrib.rst

This is needed since GitHub Actions CI/CD workflows switched their default macOS runners to `arm64` and this caused the test jobs to start running tests against pure-python wheels.
Additionally, this PR sets up Python 3.7 tests to run on older macOS 13.
Refs:
* https://github.com/psf/cachecontrol/pull/334
* https://github.com/actions/setup-python/issues/856

🧪 Build `arm64` wheels in pull requests

---

CHANGES/1033.bugfix.rst
tests/test_url.py
tests/test_url_update_netloc.py
yarl/_url.py

The changes add a missing step in rfc3986 normalization - strip default port from URL str representation.
Yes
https://github.com/aio-libs/yarl/pull/1023#discussion_r1636861213
> In the future, with another PR, I think the only normalisation step currently missing is https://datatracker.ietf.org/doc/html/rfc3986.html#section-6.2.3
> Which would include (for HTTP/HTTPS schemes) setting the path to / when empty and removing the port number when matching the default 80/443.

Normalize URL string ports per RFC 3986 section 3.2.3

---

requirements/dev.txt
requirements/doc.txt

Starting with the release of towncrier 24.7 the CI/CD regulary fails as the linter does not work.
sphinxcontrib-towncrier does have an upper boundary for the towncrier version and is incompatible to 24.7.
c.f. https://github.com/sphinx-contrib/sphinxcontrib-towncrier/issues/92
Installing tc 23.11 for docs to avoid getting 24.7.

Enforce towncrier requirements for docs to fix CI

---

.pre-commit-config.yaml

Bump black to 24.8.0
black keeps moving the mypy ignore in https://github.com/aio-libs/yarl/pull/1031 Newer versions are supposed to be better about this.

Bump black from 24.4.2 to 24.8.0

---

.github/workflows/ci-cd.yml
CHANGES.rst

Adjust ci workflow to handle the format change in 4eb7dfa05a79222472bf37802a9b90928865f635 as the 1.9.5 release failed with `KeyError: "'=' * (len(version) + 1)"`
Tested with
```
(venv) yarl % git checkout version_format_ci
Switched to branch 'version_format_ci'
(venv) yarl %  INPUT_CHANGES_FILE="CHANGES.rst" INPUT_OUTPUT_FILE="release_note.md" INPUT_VERSION_FILE="yarl/__init__.py" INPUT_START_LINE=".. towncrier release notes start" INPUT_HEAD_LINE="{version}\n=+\n\n\*\({date}\)\*\n" INPUT_FIX_ISSUE_REGEX=':issue:`(\d+)`' INPUT_FIX_ISSUE_REPL="#\1" INPUT_DIST_DIR="dist" INPUT_VERSION="" INPUT_CHECK_REF="" INPUT_NAME="yarl" python3 get_releasenote.py
::set-output name=version::1.9.5
::set-output name=prerelease::false
::set-output name=devrelease::false
```

Fix get-releasenote parsing the changelog

---

CHANGES/1067.bugfix.rst
tests/test_url.py
yarl/_url.py

This reverts commit e3dd736368790d1e4dd1d637eecc598a60216132.
This change introduced a regression with parsing the query string in joined urls. #1066 attempted to fix the regression, but when it became too involved. Since this doesn't look like there will be a quick fix, the change is being reverted so it can be tried again in the future.

Revert "RFC3986 compatible URL.join honoring empty segments (#1039)"

---

CHANGES.rst
CHANGES/1016.removal.rst
yarl/__init__.py

~~https://github.com/aio-libs/yarl/actions/runs/10642760388~~ failed. (forgot to [drop `v`](https://yarl.aio-libs.org/en/latest/contributing/release_guide/#pre-release-activities) from CHANGES.rst)
https://github.com/aio-libs/yarl/actions/runs/10643373937
Re-release to revert https://github.com/aio-libs/yarl/pull/1039 since it introduced a regression in query string handling with `%2B` (aka `+`) and url joins.
See https://github.com/aio-libs/yarl/pull/1066 for test case

Release 1.9.6

---

CHANGES/1067.bugfix.rst

I missed removing this late last night when I did the 1.9.6 release to revert the change that caused the query string decoding regression with joined URLs.

Cleanup released changelog messages

---

.coveragerc

This patch fixes the directory misattribution of test file paths by marking the entire repository directory as source.
closes #1071

🧪🚑 Fix coverage.py-included paths @ XML

---

tests/test_url.py

#1039 introduced a regression in decoding query string params with `%2B` (aka `+`). Add coverage to ensure we do not miss this again in the future.
no
#1039

Add additional coverage for joining urls

---

CHANGES/1076.breaking.rst
yarl/_url.py

Remove support [RFC 3986 section-3.2.3](https://datatracker.ietf.org/doc/html/rfc3986#section-3.2.3) port normalization when the scheme is not one of `http`, `https`, `wss`, or `ws`.
Support for port normalization was recently added in #1033 and contained code that would do blocking I/O if the scheme was not one of the four listed above. The code has been removed because this library is intended to be safe for usage with `asyncio`.
Additional details can be found in issue #1075
RFC 3986 section 3.2.3 port normalization will only work for `http`, `https`, `ws`, and `wss`
fixes #1075

Remove fallback to getservbyname in _get_default_port

---

CHANGES.rst

reference https://github.com/aio-libs/yarl/pull/1076#discussion_r1740185791

Cleanup asyncio reference in the 1.9.7 changelog

---

.codecov.yml

- prevent mypy coverage from being considered in the `patch` coverage since it decreases the coverage and blocks merges
- codecov is rounding down sometimes for `tests-pytest` so drop it to .01
no CI fix

Fix codecov blocking merges

---

.codecov.yml
CHANGES/1081.misc.rst
yarl/_url.py

There were a few places were the port got parsed out of the underlying `SplitResult` object multiple times. Make sure they are all cached to avoid doing the same work over and over.
This solves a minor performance regression that was introduced with the port normalization in #1033
performance improvement
#1033
For reference, `is_default_port` from `update_headers` in `aiohttp` is showing significantly higher on the profile with recent yarl versions.
before
after

Improve performance of handling ports in the URL

---

.codecov.yml
.coveragerc
.github/workflows/ci-cd.yml
requirements/test.txt

$sbj.
Nope.
https://github.com/aio-libs/yarl/pull/1084#discussion_r1741257263

🧪 Integrate `covdefaults` into coverage.py

---

CHANGES.rst
CHANGES/1081.misc.rst
CHANGES/1084.contrib.rst
CHANGES/1084.feature.rst
CHANGES/1086.feature.rst
yarl/__init__.py

https://github.com/aio-libs/yarl/actions/runs/10694100174
no changes since rc0 (https://github.com/aio-libs/yarl/pull/1089) -- rc0 was to do some CI runs to verify mypy was ok externally. I'm doing a release ahead of merging https://github.com/aio-libs/yarl/pull/1082 since we had an issue with it on the first go round and I'd like to make it easier to isolate if there is an issue again (hopefully not since we have since added more coverage).

Release 1.9.8

---

CHANGES.rst

It should show without the `()`s

Adjust missing type changelog message to be attr instead of meth

---

CHANGES/1100.feature.rst
docs/api.rst
tests/test_url.py
yarl/_url.py

We call `is_absolute` quite often internally and externally. Currently this requires re-parsing the `netloc`. To make the API more consistent and perform better, `absolute` is now preferred over `is_absolute`. `is_absolute` is retained for backwards compatibility.
`absolute` is now preferred over `is_absolute`, however there are no plans to remove `is_absolute`.
Probably not the best representation of a microbenchmark since `raw_host` would previous be a cache miss most of the time and this change will perform much better either way:
```
>>> timeit.timeit("x.is_absolute()", globals=locals())
0.0817429160233587
>>> timeit.timeit("x.absolute", globals=locals())
0.06663041608408093
```
On previous version when `raw_host` is a cache miss
```
>>> from yarl import URL
>>> x=URL("")
>>> …
```

Introduce absolute cached property

---

CHANGES/1084.bugfix.rst
CHANGES/1105.bugfix.rst
CHANGES/1107.bugfix.rst
yarl/_url.py

Fix non-subscriptable MultiDictProxy error as seen in #1105 when using older versions of multidict
no
fixes #1105

Fix `TypeError` with `MultiDictProxy` and Python 3.8

---

CHANGES.rst
CHANGES/1084.bugfix.rst
CHANGES/1104.misc.rst
CHANGES/1105.bugfix.rst
CHANGES/1107.bugfix.rst
yarl/__init__.py

https://github.com/aio-libs/yarl/actions/runs/10712673934
Doing another release since the issue reported in #1105 is a blocking for Python 3.8 users with an older version of `multidict`

Release 1.9.11

---

CHANGES/1117.misc.rst
yarl/_url.py

The goal is to avoid errors when pre-populating the cache
no
https://github.com/aio-libs/yarl/pull/1112#discussion_r1747515069

Add types to the internal cache

---

CHANGES/1122.misc.rst
yarl/_helpers_c.pyx

Optimize cython cached_property implementation
no
timeit: 0.0037811670918017626
before
timeit: 0.003146165981888771
after

Optimize cython cached_property implementation

---

CHANGES/1125.misc.rst
yarl/_url.py

Avoid a partition call for most cases since its rare that the host will have a IPv6 zone.  We guard all the other partitions but this one was missed, and its one of the most common in the hot path.
before total time = 0.040
100000    0.040    0.000    0.068    0.000 _url.py:907(_encode_host)
after total time = 0.031
100000    0.031    0.000    0.051    0.000 _url.py:907(_encode_host)
```
print(timeit.timeit('URL("http://user:pass@example.com?a+b=c+d").raw_host', globals=globals(), number=100000))
```
no

Small optimization to encoding hosts

---

CHANGES/1126.misc.rst
yarl/_url.py

We guard against quoting empty strings in __new__ but not in build
Quoting is the most expensive operation besides parsing IPs
no

Avoid quoting empty strings when building URLs

---

yarl/_url.py

The path being passed to replace() was always the same value that already existed

Remove useless path replacement in with_query

---

CHANGES/1126.misc.rst
CHANGES/1130.misc.rst
tests/test_update_query.py
yarl/_url.py

- Avoid reparsing the query string into a MultiDict
- Avoid creation of many intermediate MultiDict and MultiDictProxy objects
- Build the final string with iterable helper since there will never be `QueryVariable`
no

Improve performance of URL.update_query

---

yarl/_url.py

This is a small refactoring to avoid the `elif` blocks and intermediate variable since we can always return right away

Refactor _get_str_query to avoid intermediate variable

---

CHANGES/1131.misc.rst
yarl/_url.py

`_query_var` is almost never called with subclassed values, and almost everything is `str`.  All the `issubclass` calls add up with large query strings
```
0.0006691671442240477 <- is
0.0010826669167727232 <- issubclass
```
No

Optimize _query_var for ``str`` objects

---

CHANGES/1126.misc.rst
CHANGES/1128.feature.rst
docs/api.rst
tests/test_update_query.py
yarl/_url.py

Adds a new method called `extend_query` that will add additional keys instead of replacing them like `update_query`.  [The goal is to replace the hand rolled version in `aiohttp`](https://github.com/aio-libs/aiohttp/blob/11a96fcc7b62b33f0088640a05237e262cac5691/aiohttp/client_reqrep.py#L231)
no
#1127

Add extend_query method

---

CHANGES/1137.misc.rst
tests/test_normalize_path.py
tests/test_url.py
yarl/_url.py

- Replace `startswith` with a single char check. `startswith` is a good choice for multiple chars, but its much slower for single chars
- If there are no `.` in the path, don't normalize them as there is nothing to do.  In testing 80% of paths did not have a `.` so we would needless normalize them
no
timeit
startswith: 0.005655332934111357
single char check: 0.0019642498809844255
before
after

Small speed up to normalizing the path

---

CHANGES/1136.bugfix.rst
tests/test_url_parsing.py
yarl/_url.py

Allow empty hosts for schemes that do not require them
schemes other than `"http", "https", "ws", "wss", "ftp"` will not raise `ValueError` on empty host anymore
fixes #821

Allow empty hosts for schemes that do not require them

---

CHANGES/1138.bugfix.rst
CHANGES/280.bugfix.rst
tests/test_url_update_netloc.py
yarl/_url.py

`with_scheme` will now allow scheme replacement for relative urls if scheme does not require a host
bugfix
fixes #280

Allow scheme replacement for relative URLs if the target scheme does not require a host

---

CHANGES/1143.misc.rst
yarl/_url.py

Replace startswith with single char checks
startswith: 0.005655332934111357
single char check: 0.0019642498809844255
no

Small performance improvements to checking for chars in paths

---

CHANGES/1151.breaking.rst
tests/test_url.py
yarl/_url.py

This undones only the ignore part of #1057 in as we will instead add a new property called path_safe in #1150

Restore unquoting of %2F in paths

---

.github/workflows/reusable-build-wheel.yml
CHANGES/1150.feature.rst
docs/api.rst
tests/test_url.py
yarl/_url.py

Needed for https://github.com/aio-libs/aiohttp/pull/9267

Add path_safe method

---

.github/workflows/ci-cd.yml

The previous release hit the timeout of 7 minutes so the signatures did not upload.  Double the timeout to 14 minutes so this does not happen again.

Increase release timeout from 7 to 14 minutes

---

CHANGES.rst
yarl/__init__.py

https://github.com/aio-libs/yarl/actions/runs/11002449369
This is a no change release of 1.12.0 since the signatures failure to upload because the release process hit the timeout.  The timeout has now been increased to 14 minutes from 7 minutes to ensure this does not happen again.

Release 1.12.1

---

CHANGES/1163.misc.rst
tests/test_url_build.py
yarl/_url.py

Use the fast `_split_netloc` method so we do not have to reparse the netloc for every property.
Previously we called each `SplitResult` property, and each property call has to reparse the netloc every time. Only do it once
no
https://github.com/aio-libs/aiohttp/pull/9309#discussion_r1778760440 will call `URL.build` with `authority` much more often in a performance sensitive path.

Improve performance of building URLs with authority

---

CHANGES.rst
CHANGES/1163.misc.rst
yarl/__init__.py

https://github.com/aio-libs/yarl/actions/runs/11075936969
Solving the performance issue ahead of releasing the aiohttp fix in https://github.com/aio-libs/aiohttp/pull/9309#discussion_r1778760440

Release 1.13.1

---

CHANGES/1170.misc.rst
tests/test_url.py
yarl/_url.py

This is effectively the same optimization as done in #1168 for the internal `_port_not_default` cached property.  If `port` is not already cached, we avoid one property lookup.

Improve performance of converting URL to a string

---

CHANGES/1176.misc.rst
yarl/_url.py

Improve performance of _encode_host
- If we are not running the potential ip address path, avoid checking for IPv6 zone
- If the parsed address is not IPv6, avoid trying to join the IPv6 zone back to it
This one is very small, I only noticed it because I was looking over `_encode_host`
and wondering why we were looking for an IP zone outside of the ip address block
no
before
after

Improve performance of _encode_host

---

yarl/_url.py

Accessing `self._val` namedtuple is faster than using the properties even if they are cached because it avoids the call for each value
no

Cleanup some unnecessary internal property accesses

---

CHANGES.rst
CHANGES/1168.misc.rst
CHANGES/1169.packaging.rst
CHANGES/1170.misc.rst
CHANGES/1175.misc.rst
CHANGES/1176.misc.rst
CHANGES/860.contrib.rst
yarl/__init__.py

Release 1.14.0

---

tests/test_url.py

This was wrong in previous yarl releases, but fixed by one of the cleanups in 1.14.0. Add coverage to make sure it continues to work as 0 is not a default port
The problem:
`str(URL("http://example.com:0/"))` should be `http://example.com:0/` because `0` is not the default port for `http`
yarl 1.9.5 - 1.13.1 produced it as `http://example.com/`

Add test coverage for handling port 0

---

CHANGES/1189.misc.rst
tests/test_url_update_netloc.py
yarl/_url.py

Fix with_scheme checks when passed scheme is not lowercase
bugfix

Fix with_scheme checks when passed scheme is not lowercase

---

CHANGES/1190.misc.rst
yarl/_url.py

Add a cache to parsing the host when encoding hosts
split out from #1188
We tend to parse the same hosts over and over again, so cache the parsing
no

Add a cache to parsing the host when encoding hosts

---

url_benchmark.py

Add benchmark script for URLs
Right now this has the same design as `benchmark.py` which benchmarks the quoter. While this is a good starting point, ideally we use [codspeed](https://codspeed.io/) to keep track of this in the CI
no

Add benchmark script for URLs

---

url_benchmark.py

`www.domain.tld` is far more likely than `localhost.{i}`

Improve URL benchmarks to better match real world use cases

---

CHANGES/1193.misc.rst
yarl/_url.py

Roughly a 10% speed up for the tuple/list case, 5% speed up for the non sequence case
baseline
Make URL with query mapping: 0.364 sec
Make URL with query sequence mapping: 2.121 sec
this pr
Make URL with query mapping: 0.345 sec
Make URL with query sequence mapping: 1.831 sec

Improve performance of generating query strings from mappings that contain sequences

---

url_benchmark.py

SSIA
master
```
Convert URL to string: 0.094 sec
Convert URL with path to string: 0.096 sec
Convert URL with query to string: 0.141 sec
```
1.9.4
```
Convert URL to string: 0.064 sec
Convert URL with path to string: 0.042 sec
Convert URL with query to string: 0.113 sec
```
1.9.5 -- fails -- this release should probably be yanked
```
^CTraceback (most recent call last):
File "/opt/homebrew/lib/python3.12/site-packages/yarl/_url.py", line 470, in _default_port
return socket.getservbyname(scheme)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: service/proto not found
```
1.9.6
```
Convert URL to string: 0.168 sec
Convert URL with path to string: 0.160 sec
Convert URL with query to string: 0.216 sec
```

Add benchmarks to converting URLs to strings

---

yarl/_url.py

The `or` can be combined into a single expression

Use comparison chain for validating port numbers

---

CHANGES/1198.misc.rst
tests/test_url.py
yarl/_url.py

Improve performance of converting of converting URLs to strings
There was a performance regression here as shown by the benchmarks in #1197
before
```
Convert URL to string: 0.097 sec
Convert URL with path to string: 0.097 sec
Convert URL with query to string: 0.145 sec
```
after
```
Convert URL to string: 0.045 sec
Convert URL with path to string: 0.045 sec
Convert URL with query to string: 0.091 sec
```
1.9.4
```
Convert URL to string: 0.064 sec
Convert URL with path to string: 0.042 sec
Convert URL with query to string: 0.113 sec
```

Improve performance of converting of converting URLs to strings

---

yarl/_url.py

We can avoid creating lists and then converting them to tuples for all but the split case

Simplify raw_parts branching

---

.github/workflows/ci-cd.yml
CHANGES/1204.feature.rst

https://github.com/pypa/cibuildwheel/releases/tag/v2.21.2 now supports armv7l on musl
same as https://github.com/aio-libs/propcache/pull/5
armv7l wheels are now available on supported platforms

Start building armv7l wheels

---

yarl/_quoting_py.py

Combine nested if statements in quoting_py

---

CHANGES.rst
CHANGES/1188.misc.rst
CHANGES/1189.bugfix.rst
CHANGES/1190.misc.rst
CHANGES/1193.misc.rst
CHANGES/1198.misc.rst
CHANGES/1204.feature.rst
yarl/__init__.py

Expected to be the last release to support Python 3.8 (see https://github.com/aio-libs/yarl/pull/1203)

Release 1.15.0

---

.github/workflows/ci-cd.yml
requirements/test.txt
tests/test_url_benchmarks.py

Add URL benchmarks to [codspeed](https://codspeed.io/aio-libs/yarl/benchmarks)
A followup PR will integration the quoting benchmarks
The goal is to tell us when a performance regression is introduced early before it makes it to production and hopefully catch any blocking I/O

Integrate codspeed benchmarking

---

tests/test_quoting_benchmarks.py
tests/test_url_benchmarks.py

The pytest mark is a bit nicer because it is less verbose, but it has the side effect of including the pytest overhead to set up the test which may change between versions.

Fix benchmarks including pytest overhead

---

yarl/_url.py

Small speed up to making IPv6 URLs
https://codspeed.io/aio-libs/yarl/branches/strip_brackets it is ~4% but codespeed is configured to only report >= 5% change
no

Small speed up to making IPv6 URLs

---

.pre-commit-config.yaml
tests/test_quoting_benchmarks.py
tests/test_url_benchmarks.py

Note that pytest_codspeed is missing `py.typed` so its still going to be `Any` for its imports

Add typing to benchmark tests

---

yarl/_url.py

The LRU is a lot more expensive with a kwarg, and since this is the only place we encode its unlikely to ever be used anywhere else in the future. This have all of the speed up in https://github.com/aio-libs/yarl/pull/1220 and have none of the regression.

Improve performance of building non-encoded URLs

---

CHANGES/1226.misc.rst
yarl/_url.py

Use the `_from_val` method when constructing from `SplitResult` since it has a fast path to construct new `URL` objects when the source is a `SplitResult`

Speed up methods that create new URL objects

---

CHANGES/1229.misc.rst
yarl/_url.py

Avoid re-parsing the netloc when changing user/pass/host/port
Do not call `val.port`, `val.hostname`, `val.username`, or `val.password` as they reparse the netloc again, and we already have them parsed and available in our internal methods.

Avoid re-parsing the netloc when changing user/pass/host/port

---

yarl/_url.py

Add missing type for host_subcomponent to the internal cache
no
It happens that we never set this one manually so it was not noticed

Add missing type for host_subcomponent to the internal cache

---

.github/workflows/ci-cd.yml
.github/workflows/reusable-build-wheel.yml

Release [failed](https://github.com/aio-libs/yarl/actions/runs/11307702438) due to timeout waiting for wheels to build
- One group for musl
- One group for non-musl

Split wheel builds into manylinux and musllinux groups to speed up CI

---

tests/test_url_benchmarks.py

The last release failed because the tests took too long
https://github.com/aio-libs/yarl/actions/runs/11307702438/job/31449999361

Adjust many url and many hosts benchmarks to reduce CI run time

---

.github/workflows/reusable-build-wheel.yml
tests/test_quoting.py

Some of these tests take more than 25s+ when building wheels and the test times were getting to be significantly longer than the build times (almost an order of magnitude under qemu)
fixes #1237
Previous build failed due to timeout https://github.com/aio-libs/yarl/actions/runs/11307702438
no

Disable running hypothesis tests under cibuildwheel

---

.github/workflows/ci-cd.yml
.github/workflows/reusable-build-wheel.yml

#1235 should have excluded musllinux from windows and macos since this tag does not make sense on these platforms
no

Fix building musllinux wheels during release

---

.github/workflows/ci-cd.yml

#1239 reversed the condition but did not account
for manylinux wheels use an empty tag

Fix manylinux wheels not building on release

---

.github/workflows/ci-cd.yml
.github/workflows/reusable-build-wheel.yml

Reverts most of the changes to the reusable wheels workflow except one to ensure we do not duplicate the artifact name.
Moves the selection of release wheels to be done by sending wheel-tags-to-skip based on the matrix tag

Fix building wheels during release

---

.github/workflows/ci-cd.yml

When we override to split jobs between manylinux and musllinux we need to include pp* since it will also override the value in pypyproject.toml

Ensure cibuildwheel does not attempt to build pypi wheels

---

CHANGES/1234.misc.rst
yarl/_url.py

~~Not sure if this is worth it or not, but the string convert method are a bit higher than everything else~~
Seems like 71%-3x speed up is worth it
Calling urllib's urlunsplit was quite a bit more expensive than expected as seen in the benchmarks.

Improve performance of converting URL to string

---

tests/test_url_benchmarks.py

The iterations did not need to be as high to get a good repeatable test
https://codspeed.io/aio-libs/yarl/benchmarks

Reduce iterations of query string benchmarks

---

CHANGES/1248.misc.rst
tests/test_url.py
yarl/_url.py

Avoid normalizing child paths when there are no dots in the path
This one will need quite a few more tests if benchmarks shows its worth working on

Avoid normalizing child paths when there are no dots in the path

---

tests/test_url_benchmarks.py

- Checking equality
- Checking for is_default_port

Add additional benchmarks for common cases

---

yarl/_url.py

val.netloc is accessed on a namedtuple, which is much a bit faster than calling the property (even the cython version)
The bechmark only shows ~4% improvement so not worth of a changelog message

Check val.netloc instead of self.absolute internally

---

CHANGES/1256.misc.rst
yarl/_url.py

Most of the time aiohttp is passing in a MulitDict here.  This will also help a bit for `dict` without Sequence, but as not a common of a case
For historical reasons we have support for sequences inside of MulitDict even though it shouldn't happen and it would be a breaking change to remove it

Optimize building query strings with MultiDict

---

CHANGES/1259.misc.rst
yarl/_url.py

`int` was a lot more common than I expected in production.
Performance regressed in #1139 to answer feature request #945 as we didn't have performance measurements in place when that PR was made

Improve performance of constructing query strings with ``int`` values

---

yarl/_url.py

Calling _encode_host with human is quite rare and we only need to check it to avoid the idna call
This is a ~4% speed up to the common case (note that codspeed reporting threshold if 8%)
no

Optimize branching _encode_host for common case

---

yarl/_url.py

Improve performance of constructing URLs with a netloc
This is a ~3% speed up to the common case (note that codspeed reporting threshold if 8%)
no
So much of the request itself is constructing the URL, however I'm running out of thoughts on how to improve the performance here.

Improve performance of constructing URLs from unencoded string

---

yarl/_url.py

There was no need to check for `None` for the quoting

Simplify processing of username and password for unencoded URLs

---

CHANGES/1271.misc.rst
yarl/_url.py

Connecting to a non-default port, providing a username, or password in the URL is a less likely case. Optimize for the common case.

Add a fast path for URL construction when the netloc is the host

---

yarl/_url.py

The split is generally cheap because most of the time its cached, but its still better to avoid filling the cache with simple cases which make the LRU less effective.  This will speed up the many different hosts case.

Avoid splitting the netloc for simple cases when constructing URL

---

yarl/_url.py

We can avoid re-encoding the host here as well as we already have the value and all that was missing was the the IPv6 brackets

Small speed up to human_repr

---

CHANGES/1275.misc.rst
yarl/_url.py

Calling `SplitResult.port` and `SplitResult.hostname` has to re-parse the net location.  Use our internal properties instead since its very likely to already be parsed.  The speed up is tiny but it removes another case where we call `_encode_host` which makes the flow a bit easier to manage because every time we call `_encode_host` we need to think about how its going to be mutated.
#1175 did not improve the credentials/auth case as much as it could
closes #1272
related issue #1174

Improve performance of calling origin() for URLs with credentials

---

yarl/_url.py

Internal change only
I made a mistake here previously that thankfully never made it out the door... 
Make passing a value required so we always have to think about what the correct option is.  Additionally most of these calls have been eliminated because the only time we need to validate is on user input, and previously we had cases where we would validate when we already had a internally validated value.

Make validate_host a required argument to _encode_host

---

CHANGES/1265.bugfix.rst
tests/test_url_build.py
yarl/_url.py

Fix `URL.build` not validating that path has a leading slash when passing `authority`
The validation only worked when `host` was passed
Validation of leading `/` in path now works for `authority` instead of just `host` as intended

Fix `URL.build` not validating that `path` has a leading slash when passing `authority`

---

yarl/_url.py

~1% to avoid the `len()` call since truth is what we want here.

Small speed up to with_path

---

yarl/_url.py

Followup to #1271 
We can include port in the fast path as well do avoid doing a full netloc assemble when we know the username and password are None

Include port in the fast path for building the network location

---

tests/test_quoting.py

I'm working on optimizing the quoter so I want to make sure no off-by-one errors are introduced

Add test to ensure query quoter is not off by one

---

tests/test_quoting_benchmarks.py

These benchmarks should have used `PATH_QUOTER`, and since they didn't they appear to be much more expensive than a real world use case.

Fix path quoting benchmarks to use the same quoting config as production

---

tests/test_url_benchmarks.py

We didn't have any query string benchmarks

Add query string benchmarks

---

tests/test_quoting.py

The mark is already applied upstream so we do not need to apply it here
*(https://hypothesis.rtfd.io/en/latest/details.html#the-hypothesis-pytest-plugin)*
https://github.com/aio-libs/yarl/pull/1280#discussion_r1802632116

Remove redundant hypothesis pytest mark

---

tests/test_url_benchmarks.py

Add benchmark for building a URL with query

---

tests/test_url_benchmarks.py

Ideally we would look at `__wrapped__` but its not exposed on `under_cached_property,` but this is fine as it will give us a baseline to know when it changes since every call will be a cache miss.
Will give us a better idea on the actual performance impact of #1296

Fix query benchmarks to avoid testing property cache hits

---

CHANGES/1297.misc.rst
yarl/_url.py

`URL.build` had a few places left where performance could be improved
- Avoid evaluating the run time lambda created at https://github.com/python/cpython/blob/d83fcf8371f2f33c7797bc8f5423a8bca8c46e5c/Lib/collections/__init__.py#L441 
- Avoid creating the `URL` object twice when passing `query` as we already had a method to convert `query` to string, and we shouldn't make two objects to build a URL

Improve performance of `URL.build` by avoiding operations

---

tests/test_url_benchmarks.py

There is an old branch where it looks like an optimization for relative URLs was being considered so it seems important to track the performance of URLs without a host
https://github.com/aio-libs/yarl/tree/relative_url_optimized

Add benchmarks for making and building URLs without a host

---

CHANGES/1304.misc.rst
yarl/_url.py

This function was a bit hard to unpack so I have added some comments about what is going on.
Since we reconstruct nearly everything, create a new tuple instead of replacing

Small cleanups to making children paths

---

CHANGES/1305.misc.rst
yarl/_url.py

Improve performance of extend_query

Improve performance of the `URL.extend_query` method

---

tests/test_url_benchmarks.py

Since origin() is a thin shim around _origin we need to create new URLs for the benchmark to avoid
testing the cache

Fix URL.origin benchmark to avoid testing the cache

---

CHANGES/1307.misc.rst
yarl/_url.py

Most of the time here is spent rebuilding the URL. Getting rid of `_replace` makes this a lot faster

Improve performance of the `URL.with_path` method

---

yarl/_url.py

Moves the `is` check for `int` before the `issubclass` call since its very cheap. It should be a tiny bit slower for subclassed `str` but since `is` is so much faster than `issubclass` it should be de minimis

Small performance improvement for query strings with int values

---

CHANGES/1306.misc.rst
tests/test_url.py
yarl/_url.py

Improve performance of the `URL.origin` method

---

CHANGES/1308.misc.rst
yarl/_url.py

This will help a bit reassembling the URL, but not as good as `joinpath` because parsing the query string is still relatively more expensive.

Improve performance of the `URL.with_query` method

---

CHANGES/1309.misc.rst
yarl/_url.py

Improve performance of the `URL.update_query` method

Improve performance of the `URL.update_query` method

---

CHANGES/1315.misc.rst
yarl/_url.py

Avoid calling `SplitResult._replace` since its much slower

Improve performance of URL equality checks

---

CHANGES/1317.misc.rst
yarl/_url.py

Avoid calling `SplitResult._replace` since its much slower

Improve performance of with_fragment

---

CHANGES/1316.misc.rst
yarl/_url.py

Improve performance of methods that modify the network location

---

tests/test_url_benchmarks.py

There were a few methods still missing benchmarks, but since Home Assistant never calls them in production I never saw them in the profile and didn't think about writing benchmarks for them

Add missing benchmark for less common operations

---

CHANGES/1318.misc.rst
yarl/_url.py

Improve performance of calculating the URL hash

---

CHANGES/1322.misc.rst
yarl/_url.py

Improve performance of `URL.with_scheme`

---

CHANGES/1320.misc.rst
yarl/_url.py

Improve performance of URL.with_name

---

CHANGES/1319.misc.rst
yarl/_url.py

Improve performance of `URL.relative`

---

tests/test_url.py

We had a few gaps in the coverage that should be closed before optimizing this in https://github.com/aio-libs/yarl/pull/1321

Improve test coverage for `URL.parent`

---

tests/test_url.py

followup to #1324
I choose some poor names and should have checked the `parent._val` result in #1324

Additional cleanups for `URL.parent` tests

---

CHANGES/1321.misc.rst
yarl/_url.py

Improve performance of `URL.parent`

---

tests/test_url_benchmarks.py

We only had benchmarks for calling with a `Sequence` or a `Mapping`. Add one for `str`

Add benchmark for calling `update_query` with a query string

---

yarl/_url.py

- Avoid some NamedTuple property access
- Avoid creating a return variable when unneeded

Small internal code cleanups

---

yarl/_url.py

This is an internal change only now that everything is reconstructing from tuples, we can avoid having to make the `SplitResult` in a lot of places

Reduce duplicate code to construct URL from a tuple

---

CHANGES/1336.misc.rst
yarl/_url.py

Avoids the NamedTuple property accesses since we already have the values

Small performance improvement for constructng new URL objects

---

tests/test_url_benchmarks.py

Add a benchmark for accessing the raw_host with an empty cache

---

.coveragerc
tests/test_url.py

We are missing tests for
- ipv6 left bracket missing
- ipv6 right bracket missing
- ip future being bracketed
- ipv4 being backeted
- stripping unsafe url chars
- stripping control chars

Add additional test coverage for invalid URLs

---

yarl/_url.py

`cls` is unused here so it did not need to be a `classmethod`

Make _normalize_path a staticmethod

---

CHANGES/1345.misc.rst
yarl/_url.py

`classmethod`s and `staticmethod`s are slower than normal methods, and these methods never need anything on the URL objects like `_normalize_path_segments`

Break out functions that do not need decorated methods

---

tests/test_url.py

"\u2100" which normalizes to "a/c" should be tested since it could mean a `/` injection

Add additional test case for unicode decomposition normalization

---

yarl/_url.py

`staticmethod`s are a bit slower than normal methods, and this one can avoid being a `staticmethod` since it does not need anything on the class

Extract `_query_var` into its own function

---

yarl/_url.py

All of these are already in a protected namespace `_url` so they do not need to be prefixed with `_`

Cleanup constant naming in `_url.py`

---

yarl/_url.py

The `@classmethod` here is a bit slower, and it was only a `@classmethod` to access `self._QUOTER` which is a constant anyways

Extract `_make_netloc` from URL object

---

tests/test_normalize_path.py
yarl/_url.py

These do not need to be staticmethods. Ideally we can organize the code a bit more and move them into seperate modules later

Extract staticmethods from URL object

---

yarl/_quoters.py
yarl/_url.py

This will allow us to break up `_url.py` a bit more and move all the query parsing functions into their own module.
This an internal change only as all methods are in a protected namespace.

Move quoters to their own module

---

CHANGES/1357.breaking.rst
tests/test_cache.py
yarl/_url.py

There was a refactoring error in #1348 that set encode size to the decode size
Fix the bug and add coverage to ensure it does not break again.
This change never made it to a release before the problem was discovered

Fix setting the idna_encode_size

---

tests/test_url_query.py

There were a few uncovered line from splitting up the `update_query` that turned out to not have direct coverage

Add missing test coverage for `URL.update_query`

---

yarl/__init__.py
yarl/_query.py
yarl/_url.py

Move query string functions into their own module.
Doc strings have been cleaned up as well.
This is an internal change only to better organize code.
At some point we may want to add direct coverage for these functions, however they are already well covered by existing tests.

Move query string functions into their own module

---

tests/test_url_build.py

There were a few paths for `URL.build` where `encode=True` that were not fully covered.

Add missing coverage for `URL.build`

---

yarl/_parse.py
yarl/_url.py

This is an internal change only

Move URL parsing functions to their own module

---

CHANGES/1363.breaking.rst
tests/test_cache.py
yarl/_url.py

The loop variable `size` should not get redefined. Python `for` doesn't define its own scope. Add more coverage to make sure everything works as expected with the backwards compat.

Fix loop variable being redefined in `cache_configure`

---

tests/test_url.py

We are missing direct coverage for this

Add coverage for passing encoded `SplitResult` to create a `URL`

---

tests/test_url.py

There was no coverage for invalid IDNA encodings

Add coverage for invalid IDNA encoding

---

yarl/_url.py

This code is not reachable according to the tests, and I can't see how it ever could be based on how the url splitting works.  Its only reachable in `URL.build`
This was added in #243 58e6f825bcff7334e43ebc32be48d1653aa53e04 and the tests only cover `URL.build`. It looks like this previous went unnoticed because it was in a function which was reachable via `URL.build` and `URL.__new__` but the `URL.__new__` case would never raise so it still showed coverage for the line even though the `URL.__new__` case would never raise.

Remove unreachable authority absolute path check in `URL.__new__`

---

tests/test_url.py

We had no coverage for this. I wonder if it even makes sense, but it is currently supported.

Add test coverage for creating URLs from pre-encodeded str

---

CHANGES/1369.misc.rst
tests/test_url.py
yarl/_parse.py
yarl/_url.py

Now that we have own url splitting implementation, we can move the cache one level higher so we can cache more of the url encoding.
We can avoid the case where we have to reconstruct the `SplitResult` after the quoter the values since the `SplitResult` is now only generated after all the work is done.

Move `split_url` cache around encoding the URL

---

CHANGES.rst
CHANGES/1336.misc.rst
CHANGES/1342.bugfix.rst
CHANGES/1345.misc.rst
CHANGES/1348.breaking.rst
CHANGES/1357.breaking.rst
CHANGES/1363.breaking.rst
CHANGES/1369.misc.rst
yarl/__init__.py

Release 1.16.0

---

CHANGES/1340.feature.rst
docs/api.rst
tests/test_url.py
yarl/_path.py
yarl/_url.py

Support for using the subtraction operator to calculate the difference between the *paths* of two URLs. A new URL with the relative path is returned to the user.
Usage:
```py
from yarl import URL
target = URL("http://example.com/path/index.html")
base = URL("http://example.com/path/")
rel = target - base
print(rel)  # output: "index.html"
```
Now the user can easily calculate the relative path between two URLs!
Resolves #1183

Support using the subtraction operator to get the relative path between URLs

---

yarl/_url.py

Avoids some `NamedTuple` property accesses by doing a tuple unpack at the start of the function

Small performance improvement to URL subtraction

---

tests/test_url.py

We were missing coverage for this branch when looking at the pytest coverage

Add coverage for invalid IDNA A label

---

CHANGES/1382.feature.rst
yarl/_path.py

Improve performance of calculate_relative_path

---

tests/test_url_benchmarks.py

The performance is currently nearly quadratic so its good to compare a short and long url

Add benchmark for subtracting long URL paths

---

tests/test_url.py

https://github.com/aio-libs/yarl/pull/1388 will remove `PurePath` and replace it with an internal helper, however there are still some cases that are not correct that will need to be addressed.  To ensure future refactoring does not cause regressions, add more coverage.

Add more URL subtraction coverage

---

CHANGES.rst
CHANGES/1375.feature.rst
yarl/__init__.py

Release 1.17.0

---

.pre-commit-config.yaml
requirements/test.txt
tests/test_quoting_benchmarks.py
tests/test_url_benchmarks.py

Upgrade codspeed to 3.0.0

---

CHANGES/1396.misc.rst
tests/test_pickle.py
tests/test_url.py
tests/test_url_parsing.py
yarl/_parse.py
yarl/_url.py

partially implements #172
It was suggested in #172 to only upgrade to `SplitResult` when needed.  This will give us more flexibility to change how the internal structure works in the future and we won't be forever bound to using `SplitResult`.
The only place we can't fully get rid of it is for pickle without a breaking change. #172 suggested leaving it for compat, so thats what I did.
In the future we may want to change the split functions to unpack the values into named variables in future. ie `self._scheme, self._netloc, self._path, self._query, self._fragment = val` or store everything in `self._cache` as the single source of truth; However that was too large of a redesign for this PR since it would also require changing all the tuple unpacking and pre cache in `__new__`.
One …

Complete removal of `SplitResult` as an internal

---

yarl/_url.py

Small cleanups as a followup to removing `self._val`

---

yarl/_url.py

followup to #1397
- avoid `elif` blocks
- made the `__new__` code a bit more concise
- avoid some unneeded intermediate variables
- make URL object creation always happen in the same order

Additional small cleanups to as a followup to removing `self._val`

---

yarl/_parse.py
yarl/_url.py

I forgot to add this one to `_InternalURLCache`. I also realized it should have been `SplitURLType` instead of `SplitURL`

Add missing type for `_val` to `_InternalURLCache` `TypedDict`

---

tests/test_url.py
yarl/_url.py

- Avoid useless assignments
- Combine nested if statements
- Set `raw_path` in the cache since we already have it along with coverage to make sure its set correctly

Small cleanups to `encode_url`

---

yarl/_quoting_c.pyx

It turns out this can raise `ValueError` if `<Py_UCS4>-1` is out of range

Remove `noexcept` from `_restore_ch`

---

CHANGES/1413.bugfix.rst
tests/test_url.py
yarl/_url.py

This changes `URL.port` to return the explicit port instead of the default port when the explicit port is zero (i.e. not-`None` but falsy).
The `URL.port` attribute is supposed to give the port part of the URL with a scheme-based fallback, but it incorrectly used the fallback value when the given value was zero. This fixes the bug, returning the given value even when it is zero.
Fixes #1408

Correctly handle zero explicit_port

---

CHANGES/1411.bugfix.rst
CHANGES/1411.packaging.rst
CHANGES/1412.bugfix.rst
CHANGES/1412.packaging.rst
packaging/pep517_backend/_backend.py

Use latest Cython stable version, avoiding using pre-release versions.
Why? There is some issue with Cython 3.1.0a1 that is making the tests to fail.
No
Fixes https://github.com/aio-libs/yarl/issues/1411

📦 Cap Cython under Python 3.12+ below v3.1

---

yarl/_url.py

#1397 made this a bit less concise, clean it up a bit

Small cleanups to URL.join

---

CHANGES/1418.misc.rst
yarl/_url.py

- Avoid the slice for the common cases
- Avoid creating new lists
- Avoid reversing as long as possible so we do not have to insert at the front or create a new list since insert at 0 has O(n) time complexity, and append has O(1) time complexity

Improve performances of `URL.joinpath`

---

CHANGES/1422.misc.rst
yarl/_parse.py

The `or ""` check was not needed.  Avoid one branch and string copy for the common case where `scheme` is set.

Improve performance of converting a URL to a string

---

yarl/_url.py

Now that we have scheme available as `self._scheme` is should be a bit faster to avoid the extra property lookup, and a few less lines of code.
no

Remove internal `_default_port` property

---

.github/workflows/aiohttp.yml
CHANGES/1415.contrib.rst

Test aiohttp with new changes in yarl to prevent unexpected breaking changes.
fixes #534

Add aiohttp tests to CI

---

CHANGES.rst
CHANGES/111.feature.rst
CHANGES/1415.contrib.rst
CHANGES/1421.feature.rst
CHANGES/1422.misc.rst
yarl/__init__.py

Release 1.18.0

---

CHANGES/1434.misc.rst
yarl/_url.py

We end up doing the same modification to `URL` objects quite frequently. Because `URL` objects are immutable, when this happens the `self._cache` is lost and has to be reconstructed for the new `URL` object that is produced. Additionally, we had ended up with a few places where the `object.__new__(URL)` was inlined because it was faster. We can move this all behind an `lru_cache` which ensures `self._cache` is preserved if the parts are in the cache which is the common case for most applications. With this change we can centralize most of the `__new__` construction and make the code a bit more DRY.

Make `from_parts` a LRU to increase the chance we can preserve the internal cache

---

CHANGES/1432.misc.rst
yarl/_url.py

Since `aiohttp` `web_request` tends to see the same `URL`s over and over, its advantageous to cache building the `URL` objects. We currently have a cache for parsing URLs, but we did not have one for building URLs.  
We didn't have a cache on `URL.build`  because `URL.build` accepts a dict for the query which is not hashable. This is solved by constructing the query string before the cache is used. Note, that it may be better to avoid caching URLs with a query string in future but it didn't seem make enough difference in testing that it was worth the additional complexity.
Since `aiohttp` rarely `URL.build` with `encoded=False` we do not cache unencoded builds as the hit rate was < 50% in production testing.  The hit rate for https://github.com/aio-libs/aiohttp/blob/1fa237ffc9e7aa70cbabb68 …

Add a cache for building encoded URLs

---

.github/workflows/ci-cd.yml

The timeout was hit at 14 minutes and the 1.18.1 release only partially uploaded

Increase allowed upload time for the release

---

CHANGES.rst
yarl/__init__.py

1.18.1 timed out in the middle of the upload so I yanked it to ensure nobody ends up with a bad deployment because half the wheels were missing.
I was going to do a .post release but since PEP440 recommends not doing that for pre-release, and I've also had to explain what a post release is multiple times, I'm doing a .2 as its more strait-forward for humans

Release 1.18.2

---

yarl/__init__.py

PyPI uploads (not sure if its PyPI or GitHub) are experiencing issues at the moment as uploads are taking ~5x as much time as normal.  Both 1.18.1 (hit the workflow timeout) and 1.18.2 (token expired before it finished) failed to upload.
~~I'll try doing the release again tomorrow~~. Based on the upload times on `aiohappyeyeballs` on Sat Nov 30th, I expect a release would still fail.
Tracking https://github.com/pypa/gh-action-pypi-publish/issues/307

Increment version to 1.18.3.dev0

---

CHANGES/1442.bugfix.rst
CHANGES/954.bugfix.rst
tests/test_url_build.py
yarl/_url.py

Fixes a regression was introduced in https://github.com/aio-libs/yarl/pull/954 that prevented uppercase host names from working
https://github.com/aio-libs/yarl/issues/386 covered some of the paths, but we didn't have coverage for the build path
Allows uppercase hosts again
fixes #1441

Ensure ASCII host case normalization happens before validation

---

tests/test_url_benchmarks.py

We did not have the ability to write benchmarks that benchmarked the first hit because propcache did not expose the wrapped function until 0.2.1
This will give us a better idea if #1443 is worth it

Add benchmarks that bypass the cached property decorators

---

CHANGES.rst
CHANGES/1442.bugfix.rst
CHANGES/1443.misc.rst
CHANGES/954.bugfix.rst
yarl/__init__.py

benchmark change since 1.18.0 (last successful release): https://codspeed.io/aio-libs/yarl/runs/compare/673f3e7a6b39e9df22ee032d..674cb993dd045193b356dad7

Release 1.18.3

---

.github/workflows/aiohttp.yml

Add release branches to aiohttp tests matrix. Test yarl against aiohttp maintained releases branch.
Discussed in #1415

Add release branches to aiohttp tests

---

.github/workflows/ci-cd.yml

Python 3.13.1 has been released. As its rare to see performance changes in Python versions after .0, and even more rare to see them after .1 its time to start benchmarking against 3.13.1

Bump Python version for benchmarks to 3.13

---

.github/workflows/aiohttp.yml

aiohttp 3.10 is no longer being developed, and the CI is no longer being maintained, and no longer runs

Drop aiohttp 3.10 from CI

---

tests/test_quoting.py

- Adds a test that the C extensions are loaded okay.
No.

Add test that C extension is correctly loaded

---

CHANGES/1479.contrib.rst
setup.cfg

Ensure propcache 0.2.1 or later is used so the tests will pass
propcache 0.2.1 is now required
fixes #1457

Increase minimum propcache version to 0.2.1

---

CHANGES/1480.contrib.rst
docs/spelling_wordlist.txt
pytest.ini

Since we're setting (and not extending) `norecursedirs`, `.hypothesis` should also be there, otherwise we might be getting spurious warnings like the ones in [this test run](https://github.com/aio-libs/yarl/actions/runs/13787597245/job/38559648422?pr=1456#step:16:136).
No.

Add hidden folders to pytest's norecursedirs

---

tests/test_url_benchmarks.py

All the benchmarks we had were using the cache so we did not
have a good idea what the performance was here.

Add benchmark for parsing the query string

---

.github/workflows/ci-cd.yml
CHANGES/1495.feature.rst
docs/spelling_wordlist.txt

In theory the manylinux armv7l images have been [fixed](https://github.com/pypa/cibuildwheel/releases/tag/v2.23.0) with cibuildwheel so this should now work

Remove exclude for building armv7l wheels on manylinux

---

CHANGES/1493.misc.rst
yarl/_parse.py
yarl/_quoters.py
yarl/_quoting_c.pyx
yarl/_quoting_py.py
yarl/_url.py

When looking at the performance regression in #1492, I noticed that much of the time was spent in `parse_qsl`, however we do not need all the complexity of `parse_sql` since we use a very limited subset of the functionality.
We can write a faster version using the unquoter built-in to yarl with very little code.
no
n/a

Improve performance of query string parsing

---

yarl/__init__.py

waits for https://github.com/aio-libs/yarl/actions/runs/14287805338

Increment version to 1.19.1.dev0
