aio-libs/yarl

tests/test_url.py
yarl/__init__.py

Added `origin` property described in https://github.com/aio-libs/yarl/issues/3

Add origin property 

---

tests/test_quoting.py
tests/test_url.py
yarl/__init__.py
yarl/quoting.py

Refactoring

---

tests/test_url.py
tox.ini
yarl/__init__.py

Avoid doubling slashes when joining paths

---

tests/test_quoting.py
yarl/_quoting.pyx

Fix quoting

---

tests/test_url.py
yarl/__init__.py

Useful method for update existent query string in URL

URL.update_query(foo="bar") method

---

docs/api.rst

Documentation and some notes for `update_query` method.

Add documentation for update_query method

---

tests/test_url.py
yarl/__init__.py

Add `path_qs` property

---

tests/test_quoting.py
tests/test_url.py

This should fix some coverage partials (2) and the single miss on this library.

Fixed some Coverage issues.

---

tests/test_update_query.py
tests/test_url_build.py
yarl/__init__.py

Add support for relative urls with only query section #99

---

CHANGES.rst
tests/test_url.py
tests/test_url_update_netloc.py
yarl/__init__.py

Process password without user name

---

.travis.yml
Makefile
yarl/__init__.py

Fix make commands and flake errors, hotfix CI

---

CHANGES.rst
tests/test_pickle.py
tests/test_quoting.py
yarl/__init__.py
yarl/_quoting.pyx
yarl/quoting.py

Drop strict mode

---

tests/test_update_query.py
yarl/__init__.py

Fix handling of emtpy mappings in with_query

---

requirements/ci.txt
tests/test_url.py
yarl/__init__.py

Discussed in https://github.com/aio-libs/yarl/issues/148

update to idna 2008 and test

---

CHANGES.rst
tests/test_quoting.py
yarl/_quoting.pyx

Add writer, reuse static buffer if available
Code is 50-80 times faster than Pure Python version (was 4-5 times faster)

Optimization

---

CHANGES.rst
tests/test_url_build.py
yarl/__init__.py

Implement encoded=True by URL.build

---

yarl/__init__.pyi

Changes:
- annotation bug fix for query variable in methods: `build`, `with_query`, `update_query`

Query annotation bug fix

---

.travis.yml
appveyor.yml

Set 3.7 to the stable build.
Add 3.8-dev as the next dev target.

travis.yml: Update Python build versions

---

yarl/__init__.py

more informative error message

---

yarl/__init__.py

Fix the traceback on this error.
I've checked and this seems to be the only place with this problem.
No
**I think this template is slightly wrong, there doesn't seem to be a `CHANGES/` directory.**

add 'from exc' to exception

---

.pyup.yml

Remove pyup configuration

---

.azure-pipelines/deploy.yml

Fixes #363: provide `.c` files in source tarball

Cythonize tarball

---

.azure-pipelines/stage-test.yml
requirements/ci.txt
requirements/lint.txt
requirements/test.txt
requirements/wheel.txt

Reorganize dependencies

---

README.rst
docs/api.rst
docs/index.rst
docs/spelling_wordlist.txt
setup.py

Describe why booleans are not supported

Clarify bools support

---

README.rst

This adds syntax highlighting with Pygments' "pycon" (python console) lexer.
No
n/a
- [n/a] Unit tests for the changes exist
- [n/a] Add a new news fragment into the `CHANGES` folder

README syntax highlighting

---

CHANGES/464.feature
tests/test_url_build.py
yarl/__init__.py

Support URL.build() with scheme and path (creates a relative URL)

---

.github/workflows/ci.yml
CHANGES/535.bugfix

Fix x86 wheels building

---

CHANGES.rst
CHANGES/694.misc.rst
CHANGES/699.misc.rst
CHANGES/700.misc.rst
CHANGES/701.misc.rst
CHANGES/702.misc.rst
CHANGES/703.misc.rst
CHANGES/739.misc.rst
yarl/__init__.py

$sbj.
The published sdist is supposed to be buildable under Python 3.11 without any issues.
#706

Bump yarl to v1.8.1

---

README.rst

Add essential project description to Github README
No
/

Add project description to README

---

CHANGES/README.rst
docs/conf.py

This will allow using bylines in the changelog.

Integrate GH-related Sphinx roles via `extlinks`

---

setup.py

Add a changelog link to package metadata so that PyPI shows a direct link to it from the project page.
N/A

Add changelog project URL for PyPI

---

CHANGES/853.contrib.rst
docs/conf.py
requirements/doc.txt

📝🎨 Integrate MyST in Sphinx docs

---

.github/workflows/ci-cd.yml
CHANGES/1054.packaging.rst
setup.cfg

Add support and build wheels for Python 3.13.
No

Support Python 3.13

---

yarl/__init__.py

needs https://github.com/aio-libs/yarl/actions/runs/10640517112

Increment version to 1.9.6.dev0

---

CHANGES.rst
CHANGES/1070.misc.rst
CHANGES/1076.breaking.rst
yarl/__init__.py

https://github.com/aio-libs/yarl/actions/runs/10656524287

Release 1.9.7

---

docs/spelling_wordlist.txt

spelling was preventing an rc release

Add rc to the spelling wordlist

---

CHANGES.rst
CHANGES/1097.bugfix.rst
yarl/__init__.py

https://github.com/aio-libs/yarl/actions/runs/10707918848

Release 1.9.9

---

yarl/__init__.py

For new public facing feature #898

Increment version to 1.10.0.dev0

---

.github/workflows/reusable-build-wheel.yml

fixes failed release https://github.com/aio-libs/yarl/actions/runs/10744186035/job/29801876540
followup to https://github.com/aio-libs/yarl/pull/1088
<!-- Thank you for your contri

Fix merging of wheels during release process

---

CHANGES/1095.contrib.rst

https://github.com/aio-libs/yarl/pull/1095#discussion_r1747306455

Adjust formatting of changelog message for #1095

---

CHANGES.rst
CHANGES/1010.feature.rst
CHANGES/1050.feature.rst
CHANGES/1095.contrib.rst
CHANGES/1112.misc.rst
CHANGES/1113.feature.rst
CHANGES/1117.misc.rst
CHANGES/1118.bugfix.rst
CHANGES/774.feature.rst
CHANGES/898.feature.rst
yarl/__init__.py

~~https://github.com/aio-libs/yarl/actions/runs/10744186035~~ Failed due to upload/download artifact changes
~~2nd attempt: https://github.com/aio-libs/yarl/actions/runs/10746477913~~ cancelled due to https://github.com/aio-libs/yarl/pull/1121
3rd attempt: https://github.com/aio-libs/yarl/actions/runs/10747016614

Release 1.10.0

---

CHANGES/1123.misc.rst
yarl/_url.py

Simplify computing ports

---

yarl/__init__.py

for https://github.com/aio-libs/yarl/pull/1128

Increment version to 1.11.0.dev0

---

CHANGES.rst
CHANGES/1122.misc.rst
CHANGES/1123.misc.rst
CHANGES/1125.misc.rst
CHANGES/1126.misc.rst
CHANGES/1128.feature.rst
CHANGES/1130.misc.rst
CHANGES/1131.misc.rst
yarl/__init__.py

~~https://github.com/aio-libs/yarl/actions/runs/10763021030 - forgot to fix version in `CHANGES.rst`~~ 
https://github.com/aio-libs/yarl/actions/runs/10763473804

Release 1.11.0

---

CHANGES/1136.bugfix.rst
CHANGES/1138.bugfix.rst
CHANGES/1139.feature.rst

Cleanup tense of changelog messages

---

CHANGES.rst
CHANGES/1136.bugfix.rst
CHANGES/1137.misc.rst
CHANGES/1138.bugfix.rst
CHANGES/1139.feature.rst
CHANGES/280.bugfix.rst
yarl/__init__.py

https://github.com/aio-libs/yarl/actions/runs/10780442082

Release 1.11.1

---

CHANGES.rst
CHANGES/1143.misc.rst
CHANGES/1150.feature.rst
CHANGES/1151.breaking.rst
yarl/__init__.py

https://github.com/aio-libs/yarl/actions/runs/11000860360

Release 1.12.0

---

docs/api.rst

Add versionadded to path_safe

---

CHANGES.rst
CHANGES/1157.bugfix.rst
CHANGES/1158.bugfix.rst
CHANGES/1159.feature.rst
CHANGES/880.bugfix.rst
CHANGES/954.bugfix.rst
yarl/__init__.py

https://github.com/aio-libs/yarl/actions/runs/11061357556

Release 1.13.0

---

yarl/__init__.py

Increment version to 1.14.1.dev0

---

url_benchmark.py

baseline
Make URL with query mapping: 0.364 sec
Make URL with query sequence mapping: 2.121 sec

Add benchmarks for with_query

---

yarl/_url.py

This was the only untyped list

Improve typing for _make_child

---

yarl/_quoting_c.pyi

Remove unused code in _quoting_c.pyi

---

yarl/_url.py

Replace not with not equal operator in _validate_authority_uri_abs_path

---

yarl/_url.py

Collapse multiple statements that can be replaced with ternary operators

---

tests/test_quoting_benchmarks.py
tests/test_url_benchmarks.py

Add benchmarks for quoting to codspeed
For now we are only testing the cython versions

Add quoting benchmarks

---

yarl/_url.py

Remove unused requote argument from _make_netloc

---

tests/test_url_benchmarks.py

Add additional URL benchmarks for altering URLs

---

CHANGES/1222.misc.rst
yarl/_url.py

Improve URL.build performance
no

Improve URL.build performance

---

CHANGES.rst
CHANGES/1222.misc.rst
CHANGES/1226.misc.rst
CHANGES/1229.misc.rst
yarl/__init__.py

Release 1.15.1

---

.github/workflows/ci-cd.yml
.github/workflows/reusable-build-wheel.yml
tests/test_quoting.py

#1238 did not work as expected, and the tests still ran

Fix hypothesis still running during wheel build

---

tests/test_url_benchmarks.py

Add more benchmarks for common aiohttp calls

Add more benchmarks for common aiohttp calls

---

tests/test_url_benchmarks.py

Adds a benchmark for `URL(...) / path`

Add benchmark for truediv path joins

---

tests/test_url_benchmarks.py

Add some additional extend_query benchmarks for common cases

Add some additional extend_query benchmarks for common cases

---

yarl/_url.py

Avoid some string copy in extend_query
Performance is unchanged, but it is less code

Avoid some string copy in extend_query

---

tests/test_url_benchmarks.py

Add benchmarks for empty username and password

---

tests/test_url_benchmarks.py

Add benchmark for human_repr

---

tests/test_url_benchmarks.py

Add benchmarks for calling origin() on a URL with credentials

---

yarl/__init__.py

Increment version to 1.15.4.dev0

Increment version to 1.15.4.dev0

---

tests/test_quoting_benchmarks.py

Add more quoting benchmarks

---

tests/test_quoting_benchmarks.py

Add unquoting benchmarks

---

tests/test_url_benchmarks.py

- Add benchmarks for clearing the query string using with_query
- Add a benchmark for subclassed strings

Improve query string benchmarking

---

CHANGES/1313.misc.rst
yarl/_url.py

This should significantly improve the performance of `URL.join`

Refactor `URL.join` to avoid intermediate dict

---

tests/test_url_benchmarks.py

Add update_query benchmarks

---

README.rst

`codspeed` has been very helpful at validating performance enhancements.   Its nice that they provide the service free for OSS, so we should recognize their support.

Add codspeed badge to README

---

tests/test_url.py

We did not have any tests for disallowed unicode characters

Add tests for disallowed unicode characters

---

yarl/_url.py

Remove unused sentinel code

---

yarl/_quoters.py
yarl/_url.py

This is an internal change only

Move human_quote into the quoters module

---

tests/test_normalize_path.py
yarl/_path.py
yarl/_url.py

This is an internal change only

Move path functions into their own module

---

yarl/__init__.py

Increment version to 1.16.1.dev0

---

yarl/__init__.py

Bump version to 1.17.0.dev0

---

tests/test_url_benchmarks.py

Add benchmarks for url subtraction

---

CHANGES/1379.feature.rst
yarl/_path.py

- Use slice for single char check
- Avoid extra list creation

Small optimizations to calculate_relative_path

---

tests/test_url.py

I'm trying to improve the performance of this, but I don't want to break anything so I'm adding coverage ahead of trying to optimize it.

Add more URL subtraction tests

---

tests/test_url.py

https://github.com/aio-libs/yarl/pull/1389#issuecomment-2437342109 https://github.com/aio-libs/yarl/pull/1388#issuecomment-2437314020

Add xfail tests for URL subtraction with empty segments

---

CHANGES/1396.misc.rst

Fix grammar in #1396 changelog fragment

---

yarl/__init__.py

waits for https://github.com/aio-libs/yarl/actions/runs/11601497720
SSIA

Increment version to 1.17.2.dev0

---

CHANGES.rst
CHANGES/1411.bugfix.rst
CHANGES/1411.packaging.rst
CHANGES/1412.bugfix.rst
CHANGES/1412.packaging.rst
CHANGES/1413.bugfix.rst
CHANGES/1414.feature.rst
CHANGES/1418.misc.rst
yarl/__init__.py

Release 1.17.2

---

.github/workflows/ci-cd.yml

Reverts aio-libs/yarl#1425
https://github.com/codecov/codecov-action/issues/1683#issuecomment-2488916683 should be fixed now
closes #1426

Revert "Temporarily downgrade codecov-action to 5.0.3 to fix CI"

---

.github/actions/cache-keys/action.yml
.github/workflows/aiohttp.yml
.github/workflows/ci-cd.yml
.github/workflows/reusable-linters.yml
CHANGES/1471.contrib.rst

Fixes the windows caching by copying https://github.com/aio-libs/frozenlist/pull/633

Switch caching to use re-actors/cache-python-deps

---

.github/workflows/reusable-build-wheel.yml

copied from https://github.com/aio-libs/propcache/pull/95

Add qemu workaround to fix wheel builds

---

CHANGES.rst
CHANGES/1456.feature.rst
CHANGES/1456.packaging.rst
yarl/__init__.py

Release 1.20.0

---

yarl/__init__.py

wait for https://github.com/aio-libs/yarl/actions/runs/15546832830

Increment version to 1.20.2.dev0

---

pyproject.toml
yarl/_quoting_c.pyx

- Move Cython compiler directives from top-level comments in `.pyx` files to `pyproject.toml`
No.

Add compiler directives to pyproject.toml

---

CHANGES.rst
CHANGES/1535.contrib.rst
CHANGES/1536.contrib.rst
CHANGES/1560.contrib.rst
yarl/__init__.py

minor bump for For 3.14t wheels

Release 1.21.0

---

CHANGES.rst
CHANGES/1516.feature.rst
yarl/__init__.py

Another release for the windows arm wheels

Release 1.22.0
